spring:
  datasource:
    url: jdbc:postgresql://db:5432/warehouse
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate