app:
  scheduling:
    enabled: true
    optimization: true  # Включаем оптимизированный режим

  scheduler:
    price-update:
      interval-ms: 60000  # 1 час (увеличиваем интервал)
      initial-delay-ms: 10000 # Задержка перед первым запуском
      batch-size: 20000     # Согласовано с optimization.batch-size
      mode: batch        # Режим работы (simple/batch/bulk)

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:h2:file:./movchandb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000 # Оптимизация для пакетных операций

# Добавленные настройки для Actuator и метрик
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics  # Включенные endpoints
      base-path: /actuator  # Базовый путь (по умолчанию)
  endpoint:
    health:
      show-details: always  # Подробная информация о health
    prometheus:
      enabled: true  # Включение Prometheus endpoint
  metrics:
    tags:
      application: warehouse-app  # Глобальные теги для всех метрик
    export:
      prometheus:
        enabled: true  # Включение экспорта в Prometheus
    distribution:
      percentiles-histogram:
        http.server.requests: true  # Гистограммы для HTTP-запросов

logging:
  level:
    com.example.warehouse: DEBUG
    org.springframework.boot.actuate: INFO  # Логирование для Actuator